apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-classification
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mrdupadupa/image_generator.git
    # example of GitHub: repoURL: https://github.com/simaattar2003/simras.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
